spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/dailyservercheck?serverTimezone=Asia/Seoul
    username: root
    password: 1346520ASd!
#    password: admin
  devtools:
    livereload:
      enabled: true
    thymeleaf:
      cache: false
    restart:
      enabled: true
mybatis:
  mapper-locations: classpath:mapper/**/*.xml